// AUTO-GENERATED by fix-tsc-v2.js
// Minimal typings to satisfy build. Replace with real implementation if needed.
export type FilterValue = any;

// You can add real helpers here if the project relies on them at runtime.
