import { Paciente } from "app/modules/paciente/shared/paciente.model";
import { FieldFile } from "app/shared/models/file.model"; 

import { BaseResourceModel } from "app/shared/models/base-resource.model"; 

export class Avaliacao extends BaseResourceModel {
    id?: any;
    paciente?: Paciente;
    dataAvaliacao?: any;
    tipo?: string;
    localSintoma?: FieldFile;
    sintomasAtuais?: string;
    sintomasPresentesDesde?: string;
    situacaoSintomas?: string;
    sintomasResultado?: string;
    sintomasInicio?: string;
    localInicioSintomas?: string;
    localSintomasConstantes?: string;
    localSintomasIntermitentes?: string;
    pioraAcao?: string;
    pioraMomento?: string;
    melhoraAcao?: string;
    melhoraMomento?: string;
    disturbioSono?: string;
    travesseiro?: string;
    posicaoDormir?: string;
    tipoColchao?: string;
    episodiosAnteriores?: string;
    anoPrimeiroEpisodio?: number;
    historiaPreviaColuna?: string;
    tratamentosAnteriores?: string;
    ocorreDor?: string;
    funcionamentoBexiga?: string;
    funcionamentoIntestino?: string;
    modoAndar?: string;
    medicacaoConsumida?: string;
    complementoMedicacao?: string;
    situacaoSaudeGeral?: string;
    comorbidades?: string;
    complementoSaudeGeral?: string;
    historicoCancer?: string;
    historicoTrauma?: string;
    cirurgiaRecente?: string;
    cirurgiaGrandePorte?: string;
    complementoCirurgia?: string;
    imagens?: string;
    dorDuranteNoite?: string;
    acidentes?: string;
    perdaInexplicavelPeso?: string;
    outrosRelatos?: string;
    objetivosExpectativas?: string;
    posturaSentada?: string;
    mudancaPostura?: string;
    posturaEmPe?: string;
    posturaLateralShifi?: string;
    desvioRelevante?: string;
    observacaoPostura?: string;
    deficitMotor?: string;
    reflexos?: string;
    deficitSensorial?: string;
    sinaisDura?: string;
    perdaMovFlexao?: string;
    sintomaFlexao?: string;
    perdaMovExtensao?: string;
    sintomaExtensao?: string;
    perdaMovDeslocLatDir?: string;
    sintomaDeslocLatDir?: string;
    perdaMovDeslocLatEsq?: string;
    sintomaDeslocLatEsq?: string;
    perdaMovOutro?: string;
    sintomaOutro?: string;
    sintomasPreTesteEmPe?: string;
    sintomasPreTesteFEP?: string;
    sintomasPreTesteFEPRep?: string;
    sintomasPosTesteFEPRep?: string;
    sintomasPreTesteEEP?: string;
    sintomasPreTesteEEPRep?: string;
    sintomasPosTesteEEPRep?: string;
    sintomasPreTesteDeitado?: string;
    sintomasPreTesteFD?: string;
    sintomasPreTesteFDRep?: string;
    sintomasPreTesteED?: string;
    sintomasPreTesteEDRep?: string;
    sintomasPosTesteEDRep?: string;
    sintomasPreTeste?: string;
    sintomasPreTesteDLEPD?: string;
    sintomasPreTesteDLEPDRep?: string;
    sintomasPreTesteDLEPE?: string;
    sintomasPreTesteDLEPERep?: string;
    sintomasPosTesteDLEPERep?: string;
    sintomasPreTesteOutrosMovi?: string;
    sintomasPosTesteOutrosMovi?: string;
    testeSentar?: string;
    testeSentarComplemento?: string;
    outrosTestes?: string;
    derangement?: string;
    direcionalPreference?: string;
    dysfunction?: string;
    outrosSubgrupo?: string;
    fatoresCondDorIncapa?: string;
    educacao?: string;
    tipoExercicio?: string;
    equipamentoIndicado?: string;
    principioExtensao?: string;
    principioLateral?: string;
    principioFlexao?: string;
    outrosExerciciosInterv?: string;
    frequencia?: string;
    barreirasRecuperacao?: string;
    objetivosTratamento?: string;

    static fromJson(jsonData: any): Avaliacao{ 
        return Object.assign(new Avaliacao(), jsonData); 
    } 
}

