import { body, check, query } from 'express-validator'; 
import { validateCNPJ, validateCPF } from '../../database/validators'; 

export const createNewAvaliacaoValidator = [ 
    body('paciente')
    .exists({ checkFalsy: true }).withMessage({ messageCode: "FIELD_REQUIRED", metaData: { field: "paciente" } })
,    body('dataAvaliacao')
    .exists({ checkFalsy: true }).withMessage({ messageCode: "FIELD_REQUIRED", metaData: { field: "dataAvaliacao" } })
.isISO8601().withMessage({
        messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "dataAvaliacao" } }).toDate() 
,    body('tipo')
,    body('localSintoma')
,    body('sintomasAtuais')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasAtuais", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasAtuais" } }) 
,    body('sintomasPresentesDesde')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPresentesDesde", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPresentesDesde" } }) 
,    body('situacaoSintomas')
,    body('sintomasResultado')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasResultado", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasResultado" } }) 
,    body('sintomasInicio')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasInicio", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasInicio" } }) 
,    body('localInicioSintomas')
,    body('localSintomasConstantes')
,    body('localSintomasIntermitentes')
,    body('pioraAcao')
,    body('pioraMomento')
,    body('melhoraAcao')
,    body('melhoraMomento')
,    body('disturbioSono')
,    body('travesseiro')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "travesseiro", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "travesseiro" } }) 
,    body('posicaoDormir')
,    body('tipoColchao')
,    body('episodiosAnteriores')
,    body('anoPrimeiroEpisodio')
    .isLength({ max: 4 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "anoPrimeiroEpisodio", max_length: 4 } })
.isNumeric().withMessage({
       messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "anoPrimeiroEpisodio" } }).toInt()
,    body('historiaPreviaColuna')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "historiaPreviaColuna", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "historiaPreviaColuna" } }) 
,    body('tratamentosAnteriores')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "tratamentosAnteriores", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "tratamentosAnteriores" } }) 
,    body('ocorreDor')
,    body('funcionamentoBexiga')
,    body('funcionamentoIntestino')
,    body('modoAndar')
,    body('medicacaoConsumida')
,    body('complementoMedicacao')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "complementoMedicacao", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "complementoMedicacao" } }) 
,    body('situacaoSaudeGeral')
,    body('comorbidades')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "comorbidades", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "comorbidades" } }) 
,    body('complementoSaudeGeral')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "complementoSaudeGeral", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "complementoSaudeGeral" } }) 
,    body('historicoCancer')
,    body('historicoTrauma')
,    body('cirurgiaRecente')
,    body('cirurgiaGrandePorte')
,    body('complementoCirurgia')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "complementoCirurgia", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "complementoCirurgia" } }) 
,    body('imagens')
,    body('dorDuranteNoite')
,    body('acidentes')
,    body('perdaInexplicavelPeso')
,    body('outrosRelatos')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "outrosRelatos", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "outrosRelatos" } }) 
,    body('objetivosExpectativas')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "objetivosExpectativas", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "objetivosExpectativas" } }) 
,    body('posturaSentada')
,    body('mudancaPostura')
,    body('posturaEmPe')
,    body('posturaLateralShifi')
,    body('desvioRelevante')
,    body('observacaoPostura')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "observacaoPostura", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "observacaoPostura" } }) 
,    body('deficitMotor')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "deficitMotor", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "deficitMotor" } }) 
,    body('reflexos')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "reflexos", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "reflexos" } }) 
,    body('deficitSensorial')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "deficitSensorial", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "deficitSensorial" } }) 
,    body('sinaisDura')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sinaisDura", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sinaisDura" } }) 
,    body('perdaMovFlexao')
,    body('sintomaFlexao')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomaFlexao", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomaFlexao" } }) 
,    body('perdaMovExtensao')
,    body('sintomaExtensao')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomaExtensao", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomaExtensao" } }) 
,    body('perdaMovDeslocLatDir')
,    body('sintomaDeslocLatDir')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomaDeslocLatDir", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomaDeslocLatDir" } }) 
,    body('perdaMovDeslocLatEsq')
,    body('sintomaDeslocLatEsq')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomaDeslocLatEsq", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomaDeslocLatEsq" } }) 
,    body('perdaMovOutro')
,    body('sintomaOutro')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomaOutro", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomaOutro" } }) 
,    body('sintomasPreTesteEmPe')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteEmPe", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteEmPe" } }) 
,    body('sintomasPreTesteFEP')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteFEP", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteFEP" } }) 
,    body('sintomasPreTesteFEPRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteFEPRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteFEPRep" } }) 
,    body('sintomasPosTesteFEPRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPosTesteFEPRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPosTesteFEPRep" } }) 
,    body('sintomasPreTesteEEP')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteEEP", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteEEP" } }) 
,    body('sintomasPreTesteEEPRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteEEPRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteEEPRep" } }) 
,    body('sintomasPosTesteEEPRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPosTesteEEPRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPosTesteEEPRep" } }) 
,    body('sintomasPreTesteDeitado')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteDeitado", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteDeitado" } }) 
,    body('sintomasPreTesteFD')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteFD", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteFD" } }) 
,    body('sintomasPreTesteFDRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteFDRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteFDRep" } }) 
,    body('sintomasPreTesteED')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteED", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteED" } }) 
,    body('sintomasPreTesteEDRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteEDRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteEDRep" } }) 
,    body('sintomasPosTesteEDRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPosTesteEDRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPosTesteEDRep" } }) 
,    body('sintomasPreTeste')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTeste", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTeste" } }) 
,    body('sintomasPreTesteDLEPD')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteDLEPD", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteDLEPD" } }) 
,    body('sintomasPreTesteDLEPDRep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteDLEPDRep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteDLEPDRep" } }) 
,    body('sintomasPreTesteDLEPE')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteDLEPE", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteDLEPE" } }) 
,    body('sintomasPreTesteDLEPERep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteDLEPERep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteDLEPERep" } }) 
,    body('sintomasPosTesteDLEPERep')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPosTesteDLEPERep", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPosTesteDLEPERep" } }) 
,    body('sintomasPreTesteOutrosMovi')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPreTesteOutrosMovi", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPreTesteOutrosMovi" } }) 
,    body('sintomasPosTesteOutrosMovi')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "sintomasPosTesteOutrosMovi", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "sintomasPosTesteOutrosMovi" } }) 
,    body('testeSentar')
,    body('testeSentarComplemento')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "testeSentarComplemento", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "testeSentarComplemento" } }) 
,    body('outrosTestes')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "outrosTestes", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "outrosTestes" } }) 
,    body('derangement')
,    body('direcionalPreference')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "direcionalPreference", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "direcionalPreference" } }) 
,    body('dysfunction')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "dysfunction", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "dysfunction" } }) 
,    body('outrosSubgrupo')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "outrosSubgrupo", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "outrosSubgrupo" } }) 
,    body('fatoresCondDorIncapa')
,    body('educacao')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "educacao", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "educacao" } }) 
,    body('tipoExercicio')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "tipoExercicio", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "tipoExercicio" } }) 
,    body('equipamentoIndicado')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "equipamentoIndicado", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "equipamentoIndicado" } }) 
,    body('principioExtensao')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "principioExtensao", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "principioExtensao" } }) 
,    body('principioLateral')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "principioLateral", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "principioLateral" } }) 
,    body('principioFlexao')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "principioFlexao", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "principioFlexao" } }) 
,    body('outrosExerciciosInterv')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "outrosExerciciosInterv", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "outrosExerciciosInterv" } }) 
,    body('frequencia')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "frequencia", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "frequencia" } }) 
,    body('barreirasRecuperacao')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "barreirasRecuperacao", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "barreirasRecuperacao" } }) 
,    body('objetivosTratamento')
    .isLength({ max: 255 }).withMessage({ messageCode: "VALIDATION_FAILED_LENGTH", metaData: { field: "objetivosTratamento", max_length: 255 } })
    .isString().withMessage({ messageCode: "VALIDATION_FAILED_FORMAT", metaData: { field: "objetivosTratamento" } }) 
,  ]; 

export const findAllAvaliacaoValidator = [ 
    query('page') 
        .optional() 
        .isNumeric() 
        .withMessage({ 
            messageCode: 'VALIDATION_FAILED_FORMAT', 
            metaData: { field: 'page' } 
        }), 
    query('limit') 
        .optional() 
        .isNumeric() 
        .withMessage({ 
            messageCode: 'VALIDATION_FAILED_FORMAT', 
            metaData: { field: 'limit' } 
        }) 
  ]; 
